version: "3.0"
services:
  mysql5:
    #build: ./mysql51
    image: nanasess/mysql51:latest
    container_name: amp4_db
    ports:
     - "3308:3306"
    restart: always
    volumes:
     - mysql_data:/mysql51
     - ../../data/mysql:/data
    environment:
     - MYSQL_ROOT_PASSWORD=demo
     - MYSQL_HOST=localhost
     - MYSQL_PORT=3306
     - MYSQL_USER=david
     - MYSQL_PASSWORD=demo
     - MYSQL_DATABASE=mysql
     - MYSQL_MY_DATABASE=factory

  phttpd253:
    #build: ./apache2php53
    image: bylexus/apache-php53:latest
    container_name: amp4_web
    ports:
     - "8090:80"
    privileged: true
    volumes:
     - ../../web:/var/www
     - ../../includes:/usr/share/php/puzzle
     #- ./php.ini:/etc/php.ini
     - ./apache2.conf:/etc/apache2/apache2.conf
     - ./common.conf:/etc/apache2/sites-enabled/common.conf
     #- ../../log/php_error.log:/var/log/php_error.log
    links:
     - mysql5:mysql

volumes:
  mysql_data:

